"""daily_sentiment sentiment_extreme (M8 Option C)

Revision ID: 0de595dd33fb
Revises: c58076172a05
Create Date: 2026-06-14 09:20:56.797756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de595dd33fb'
down_revision: Union[str, Sequence[str], None] = 'c58076172a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_sentiment', sa.Column('sentiment_extreme', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_sentiment', 'sentiment_extreme')
    # ### end Alembic commands ###
